### PR TITLE
Add hello world

### PR DESCRIPTION
**Pull request by srenatus**
Building on what @stevejb71 started, this could be our hello-world. LMK if there's anything needed.

You would check the tests with `idris --testpkg HelloWorld.ipkg`, and I'm not sure where to put that information.

(Just starting out with Idris myself, but this seems to work.)

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks! This looks good to me. What do you think, @stevejb71?

**Comment by stevejb71** [comment]
Looks good to me too.

**Comment by stevejb71** [comment]
Might be good to have a Makefile, or some standard way of building & running tests.

**Comment by srenatus** [comment]
Does exercism have any convention to follow here? `make test`? 😃

**Comment by stevejb71** [comment]
Each stream follows its own conventions (so Rust for example uses cargo which is the standard package).
I don't know of anything standard for Idris, so make seems a reasonable substitute - and make test as a target also ok.

**Comment by yurrriq** [comment]
`idris --testpkg` or similar (in away from my machine atm) is typical in Idris.

**Comment by yurrriq** [comment]
While not formally standardized, [this `Makefile`](https://github.com/jfdm/idris-testing/blob/master/Makefile) is a good example.

**Comment by srenatus** [comment]
✅ Added a simple Makefile (thanks @yurrriq)

**Comment by stevejb71** [comment]
I made a small nitpick, but not a blocker. Think it should be good to merge.

**Comment by srenatus** [comment]
@stevejb71 I can't seem to find it. Did you save it (or "finish the review")?

Also, I'm away from keyboard for a week... so I won't be able to address your nitpick promptly, sorry.

**Comment by yurrriq** [comment]
I'd like to use `sourcedir` and put `HelloWorld.idr` in a directory `src/`. Soon, probably today. I'll make a PR on your fork with that and my other ideas. I think `hello-world` is a great exercise for us to formulate a pattern for future exercises.

**Comment by srenatus** [comment]
Picking this up again with a commit (if you've branched off, sorry, I've squashed some) -- @yurrriq @stevejb71 how about this? 😃

**Comment by stevejb71** [comment]
From discussions in x-common, hello world will be changed to remove the argument, to be as simple as possible for newcomers.  

However the changes haven't been committed yet, so I'd say let's merge, and get the stream started.

**Comment by yurrriq** [comment]
I'll review for real today. Thanks for this. :+1: to getting started now and updating as needed later.

**Comment by yurrriq** [comment]
Thanks!

**Pull request merged**
