### PR TITLE
Add Leap exercise

### PR DESCRIPTION
**Pull request by stevejb71**
WIP (having trouble running ```make test``` for both this and the HelloWorld exercise, so untested).

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks. I've got some ideas in the works for testing. For now, please name the example file `example.idr` in `exercises/leap-year` or whatever. You may have already. I'm commenting before reading.

**Comment by yurrriq** [comment]
Can we rename `leap` to `isLeap`? I'd like to prefix Boolean predicates with `is`, I think.

**Comment by yurrriq** [comment]
Also, I think we should add a `src/Leap.idr` file with a skeleton module, something like:

```idris
module Leap

isLeap : Int -> Bool
isLeap year = ?isLeap_rhs
```

We should do something similar (and uniform) for all exercises, I think.

**Comment by yurrriq** [comment]
I've got a nice, CI-friendly testing strategy worked out on [tdd-with-idris](https://github.com/yurrriq/tdd-with-idris) and plan to adapt something similar for `xidris`.

Re: skeleton modules and holes, see code/discussion on [idris-hackers/software-foundations](https://github.com/idris-hackers/software-foundations).

**Comment by stevejb71** [comment]
I agree with adding a type hole, at least for the initial few exercises.
Also changed ```leap``` to ```isLeap```, and fixed a mistake in one of the tests.

**Comment by yurrriq** [comment]
This looks good. Thanks!

**Pull request merged**
